package com.example.seckill_system.service;

import com.example.seckill_system.vo.RespBean;
import javax.servlet.http.HttpServletResponse;

/**
 * Seckill Service Interface
 * 
 * <p>This interface defines the contract for all seckill-related operations in the system.
 * It provides methods for activity preheating, captcha generation, token management,
 * and the core seckill execution logic.</p>
 * 
 * <p><b>Service Responsibilities</b>:</p>
 * <ul>
 *   <li>Activity preheating: Load data into Redis before seckill starts</li>
 *   <li>Security: Captcha generation and token management</li>
 *   <li>Stock management: Atomic stock reduction using Redis Lua scripts</li>
 *   <li>Async processing: Message queueing for order creation</li>
 * </ul>
 * 
 * <p><b>Implementation</b>:</p>
 * <p>The main implementation is {@link com.example.seckill_system.service.impl.SeckillServiceImpl},
 * which uses Redis for caching, Lua scripts for atomicity, and RabbitMQ for async processing.</p>
 * 
 * @author Ai Yuyang
 * @see com.example.seckill_system.service.impl.SeckillServiceImpl
 */
public interface ISeckillService {

    /**
     * Preheats (preloads) seckill activity data into Redis cache.
     * 
     * <p>This method should be called before a seckill activity starts to ensure
     * all data is ready in Redis for fast access during the seckill period.</p>
     * 
     * <p><b>What Gets Cached</b>:</p>
     * <ul>
     *   <li>Activity object as JSON</li>
     *   <li>Stock count as string</li>
     * </ul>
     * 
     * @param activityId The ID of the activity to preheat
     * @throws com.example.seckill_system.exception.GlobalException if activity doesn't exist or has no stock
     */
    void prepareSeckill(Long activityId);

    /**
     * Generates and returns a captcha image for the specified user and activity.
     * 
     * <p>The captcha is an arithmetic expression (e.g., "3 + 5 = ?") that helps
     * prevent automated bot attacks. The answer is stored in Redis with a 5-minute TTL.</p>
     * 
     * @param userId The user ID requesting the captcha
     * @param activityId The activity ID the captcha is for
     * @param response HTTP response object to write the image to
     * @throws com.example.seckill_system.exception.GlobalException if userId or activityId is null
     */
    void getCaptcha(Long userId, Long activityId, HttpServletResponse response);

    /**
     * Verifies captcha and generates a one-time seckill token.
     * 
     * <p>This method combines captcha verification and token generation into a single
     * atomic operation. The token is required for executing the seckill request.</p>
     * 
     * <p><b>Token Characteristics</b>:</p>
     * <ul>
     *   <li>Random UUID (32 hex characters)</li>
     *   <li>User-specific and activity-specific</li>
     *   <li>60-second TTL</li>
     *   <li>One-time use (validated then used)</li>
     * </ul>
     * 
     * @param userId The user ID requesting the token
     * @param activityId The activity ID the token is for
     * @param verifyCode The captcha answer provided by the user
     * @return RespBean containing the seckill token on success
     */
    RespBean getSeckillPath(Long userId, Long activityId, String verifyCode);

    /**
     * Executes the seckill operation - the core method of the entire system.
     * 
     * <p>This method implements the critical seckill logic with multiple layers of
     * validation and optimization to handle high concurrency while preventing over-selling.</p>
     * 
     * <p><b>Execution Steps</b>:</p>
     * <ol>
     *   <li>Validate seckill token</li>
     *   <li>Check local cache flag (fast path)</li>
     *   <li>Execute Redis Lua script (atomic stock reduction)</li>
     *   <li>Send message to RabbitMQ (async order creation)</li>
     *   <li>Return "In queue" response</li>
     * </ol>
     * 
     * @param userId The user ID executing the seckill
     * @param activityId The activity ID to seckill
     * @param token The seckill token (must be generated by getSeckillPath)
     * @return RespBean with "In queue" message on success
     * @throws com.example.seckill_system.exception.GlobalException if token is invalid, stock is insufficient, or user already purchased
     */
    RespBean doSeckill(Long userId, Long activityId, String token);

    /**
     * Recovers (increments) stock in Redis for the specified activity.
     * 
     * <p>This is a compensation mechanism used when order creation fails or
     * when a duplicate order is detected. It ensures stock consistency between
     * Redis and the actual order state.</p>
     * 
     * @param activityId The activity ID to recover stock for
     */
    void recoverStock(Long activityId);

    /**
     * Verifies the captcha answer for the specified user and activity.
     * 
     * <p>This is a helper method that checks if the provided captcha answer
     * matches the answer stored in Redis. If verification succeeds, the
     * captcha is deleted from Redis (one-time use).</p>
     * 
     * @param userId The user ID
     * @param activityId The activity ID
     * @param code The captcha answer provided by the user
     * @return true if captcha is correct, false otherwise
     */
    boolean verifyCaptcha(Long userId, Long activityId, String code);
    
    /**
     * Validates a seckill token for the specified user and activity.
     * 
     * <p>This method checks if the provided token matches the token stored in Redis.
     * The token must have been generated by {@link #getSeckillPath(Long, Long, String)}
     * and not yet expired (60-second TTL).</p>
     * 
     * @param userId The user ID
     * @param activityId The activity ID
     * @param token The seckill token to validate
     * @return true if token is valid, false otherwise
     */
    boolean checkToken(Long userId, Long activityId, String token);

    /**
     * Removes the sold-out flag for the specified activity from local cache.
     * 
     * <p>This method is typically called when stock is replenished or when
     * an activity is republished. After calling this, requests for this activity
     * will flow through to Redis again instead of being rejected immediately.</p>
     * 
     * @param activityId The activity ID to clear the flag for
     */
    void removeLocalOverMap(Long activityId);
}
